/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.info6205;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek Dongare
 */
public class FirstJFrame extends javax.swing.JFrame {
  
    /**
     * Creates new form First
     */
    public FirstJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 190, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 190, -1));

        jLabel2.setText("Target");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel3.setText("Lower Limit");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 110, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 110, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 110, -1));

        jLabel4.setText("Mutual Funds");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel5.setText("Gold");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel6.setText("Diamond");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 110, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 110, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 110, -1));

        jLabel7.setText("Period");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        jLabel8.setText("Period");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel9.setText("Period");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 190, -1));

        jLabel10.setText("Upper Limit");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jTextField10.setText("$");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 130, -1));

        jLabel11.setText("Solution");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, -1, -1));

        jLabel12.setText("RESULT");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("        Particle Swarm Optimization Money Calculator");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 400, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int A=0;
        int B=0;
        int lowerlimit= Integer.parseInt(jTextField1.getText());
        int upperlimit = Integer.parseInt(jTextField9.getText());
        int goldP = Integer.parseInt(jTextField3.getText());
        int diamondP = Integer.parseInt(jTextField4.getText());
        int mutualfundsP= Integer.parseInt(jTextField5.getText());
        int gPeriod = Integer.parseInt(jTextField6.getText());
        int dPeriod = Integer.parseInt(jTextField7.getText());
          int mPeriod = Integer.parseInt(jTextField8.getText());
          int target = Integer.parseInt(jTextField2.getText());
          int bPeriod = 5;
          int noOfInputs =1;
          int noOfParticles=100;
          int noOfIterations=100;
          int x = 100-goldP;
          int y = x-diamondP;
        if(lowerlimit<0 ){
            JOptionPane.showMessageDialog(null, "Ivalid lower Limit!");
        }
        else if( upperlimit<0 || upperlimit<lowerlimit || upperlimit == lowerlimit){
            JOptionPane.showMessageDialog(null, "Ivalid Upper Limit!");
        }
       else if(target<upperlimit||target<lowerlimit || target == upperlimit){
            JOptionPane.showMessageDialog(null, "Ivalid Target!");
        }
       else if( goldP<0|| goldP>100 ){
            JOptionPane.showMessageDialog(null, "Ivalid Gold Input!");
        }
        else if( diamondP<0|| diamondP>x ){
            JOptionPane.showMessageDialog(null, "Ivalid Diamond Input!");
        }
         else if( mutualfundsP<0|| mutualfundsP>y ){
            JOptionPane.showMessageDialog(null, "Ivalid Mutual Funds Input!");
        }

        else if( gPeriod<0 ){
            JOptionPane.showMessageDialog(null, "Ivalid Gold Period Input!");
        }
       else   if( dPeriod<0 ){
            JOptionPane.showMessageDialog(null, "Ivalid Diamond Period Input!");
        }
        else   if( mPeriod<0 ){
            JOptionPane.showMessageDialog(null, "Ivalid Mutual Funds Period Input!");
        }
        
        
        
        else{
         
	
          Controller Main = new Controller(target, noOfInputs, noOfParticles, upperlimit, lowerlimit, noOfIterations, goldP, diamondP,
				mutualfundsP, gPeriod, dPeriod, mPeriod, bPeriod);
          JOptionPane.showMessageDialog(null, "Calculating");
          
            Metadata solution = Main.solution();//for passing the metadata of the thread containing optimal solution basically the optimal thread
       //created arraylist of type metadata to store the parameters of the thread as the objects. Every index of the thread will contains all the parameters of 1 thread i.e.(String threadName,Integer solution,Integer returns,boolean isOptimal)
         JOptionPane.showMessageDialog(null, "Solution Found!");
         
         if(solution.getisOptimal()){
             JOptionPane.showMessageDialog(null, " OPTIMAL Solution Found!");
             jTextField10.setText(solution.getSolution()+"");
         }
         else if(solution.getReturns()==0){
             JOptionPane.showMessageDialog(null, " OPTIMAL Solution not Found! Try updating values!" );
             
         }
         else {
             JOptionPane.showMessageDialog(null, " OPTIMAL Solution not Found! you can invest "+solution.getSolution()+" to get "+solution.getReturns());
             jTextField10.setText(solution.getSolution()+"");
             
         }
//       try {
//			Main.printSolution();
//                        JOptionPane.showMessageDialog(null, "Optimal Solution found!");
//                        jTextField10.setText("$"+Main.getOptimalSolution());
//                        
//		} catch (Exception e) {
//
//			// logic to get the next closest value
//			int[] store = new int[particles2.size()];
//
//			for (int i = 0; i < particles2.size(); i++) {
//				store[i] = particles2.get(i);
//			}
//			Arrays.sort(store);
//			System.out.println("Store 1:" + Arrays.toString(store));
//			int x = target + 5;
//			int y = target - 5;
//			for (int i = 0; i < store.length; i++) {
//
//				if (y < store[i] && store[i] < x) {
//					particles3.add(store[i]);
//				}
//			}
//			System.out.println("LIST 3" + particles3);
//			int[] store2 = new int[particles3.size()];
//			for (int i = 0; i < particles3.size(); i++) {
//				store2[i] = particles3.get(i);
//			}
//			Arrays.sort(store2);
//			for (int i = 0; i < store2.length; i++) {
//				int l = store2.length - 1;
//				A = store2[l];
//			}
//			for (Map.Entry<Integer, Integer> entry : particleTreeMap.entrySet()) {
//				int key = entry.getKey();
//				int value = entry.getValue();
//				if (A == key) {
//					B = value;
//				}
//				// System.out.println(key + " => " + value);
//			}
//			// System.out.println("Store 2" + Arrays.toString(store2));
//			System.out.println("\nSolution cannot be found!Please enter different value!");
//			System.out.println("\nInstead of " + target + " you can set target as:" + A + " and invest $:" + B);
//			// System.out.println("HashMap:" + particleMap);
//                     JOptionPane.showMessageDialog(null, "Optimal Solution not found. You can set target as:" + A + " and invest $:" + B+" or try changing the calculation values!");
//                     String numberAsString = Integer.toString(B);
//                    jTextField11.setText("$"+numberAsString);
//                     
//		}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
